version: "3.9"

services:
  web:
    build:
      context: ./myweather
      dockerfile: Dockerfile.prod
    image: advornik1986/weather_app_psql:latest
    env_file: .env.prod
    command: gunicorn myweather.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - .env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_vol:
