version: "3.9"

services:
  web:
    build: ./myweather
    image: advornik1986/weather_app_psql:latest
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myweather/:/usr/src/app/
    ports:
      - 8000:8000

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=alex
        - POSTGRES_PASSWORD=aadv1986
        - POSTGRES_DB=weather
        - POSTGRES_INITDB_AGRS "-A md5"

volumes:
  postgres_vol: